### PR TITLE
common/configure: Fix a broken build for PowerPC 32-bit

### PR DESCRIPTION
**Pull request by dmitrygx**
Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Reject this patch. Because it disabled built-in atomics for ALL platform, including x86_64.

**Comment by dmitrygx** [comment]
@HonggangLI I've updated PR. Could you verify it, please?

**Comment by ghost** [comment]
Please provide the link to your updated PR. I will test it ASAP.

**Comment by dmitrygx** [comment]
Please, use this PR. I've updated `AC_TRY_LINK` macro by `defiend(__PPC__) && !defined(__PPC64__)` - > `defined(__PPC__) && !defined(__PPC64__)`. There was typo in the **defiend**

**Comment by ghost** [comment]
git log --oneline | head -n 3
808964724b24 Merge pull request #3428 from gladkovdmitry17/verbs
c09924b361bd prov/verbs: Use only active ports
e6ece6c5bcba Merge pull request #3424 from shefty/sockets

  ~  upstream-repos  libfabric  git diff
diff --git a/configure.ac b/configure.ac
index ea2755d424cc..dcbf7d63eb76 100644
--- a/configure.ac
+++ b/configure.ac
@@ -165,7 +165,11 @@ AC_TRY_LINK([#include <stdint.h>],
     [int32_t a;
      __sync_add_and_fetch(&a, 0);
      __sync_sub_and_fetch(&a, 0);
+     #if defined(__PPC__) && !defined(__PPC64__)
        return 0;
+     #else
+      #error compiler built-in atomics are not supported on PPC32
+     #endif
     ],
     [
        AC_MSG_RESULT(yes)

Your updated PR does not make any difference. Beside compiling failed for ppc, it also disable built-in atomics for x86_64.

# x86_64 configure log
$ ./autogen.sh
$ ./configure  2>&1 | tee log.txt
$ grep ato log.txt 
checking compiler support for c11 atomics... yes
checking compiler support for built-in atomics... no  <=====

# PPC rpm building log

checking compiler support for c11 atomics... no
checking compiler support for built-in atomics... yes

libtool: link: gcc -std=gnu99 -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -mcpu=power7 -mtune=power7 -Wl,-z -Wl,relro -o util/.libs/fi_pingpong util/pingpong.o  src/.libs/libfabric.so -lrdmacm -libverbs -lnl-3 -lnl-route-3 -lrt -lpthread -ldl
src/.libs/libfabric.so: undefined reference to `__sync_add_and_fetch_8'
collect2: error: ld returned 1 exit status
make[1]: *** [util/fi_strerror] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by dmitrygx** [comment]
@HonggangLI Do you use `./configure --host ` during configuration?
I mean, if we're going to verify whether some intrinsic are supported on the configuration step we should be aware what is system/cpu building on.
https://www.gnu.org/software/autoconf/manual/autoconf-2.62/html_node/Canonicalizing.html

**Comment by ghost** [comment]
Confirmed latest patch fixed this issue. Thanks

**Comment by shefty** [comment]
@gladkovdmitry17 - I don't see that these changes made it into master.  Can you open a PR with this?

**Comment by dmitrygx** [comment]
> Can you open a PR with this?

@shefty Sure. This PR was opened to provide temporary solution to @HonggangLI 
Since I've got confirmation that this patch fixes problem, I'll prepare the PR for the libfabric.

**Pull request closed without merging**
